/* Generated by tools/build-lesson-data.js. Do not edit by hand.
   The navigation of the new site: units, lessons in order, titles, and the page of each lesson. */
window.ART_NAVIGATION = {
 "units": [
  {
   "id": "unit00",
   "title": {
    "he": "יסודות ההשראה",
    "en": "Foundations of Inspiration"
   },
   "lessons": []
  },
  {
   "id": "unit01",
   "title": {
    "he": "חוויה אישית כמקור השראה",
    "en": "Personal Experience as a Source of Inspiration"
   },
   "lessons": [
    {
     "path": "lessons/lesson-1-1.html",
     "title": {
      "he": "רגש בשפה חזותית",
      "en": "Emotion in Visual Language"
     }
    },
    {
     "path": "lessons/emotion-drawing.html",
     "title": {
      "he": "כיצד הופך רגש לציור",
      "en": "How Emotion Becomes a Drawing"
     }
    },
    {
     "path": "lessons/visual-journal.html",
     "title": {
      "he": "רגש כקומפוזיציה",
      "en": "Emotion as Composition"
     }
    },
    {
     "path": "lessons/memory-drawing.html",
     "title": {
      "he": "כיצד הופך זיכרון לציור",
      "en": "How Memory Becomes a Drawing"
     }
    },
    {
     "path": "lessons/journal-artwork.html",
     "title": {
      "he": "מה חוזר בעבודות שלי?",
      "en": "What Keeps Returning in My Work?"
     }
    },
    {
     "path": "lessons/frida-kahlo.html",
     "title": {
      "he": "אמנים כהשראה, פרידה קאלו",
      "en": "Artists as Inspiration, Frida Kahlo"
     }
    },
    {
     "path": "lessons/experience-experiments.html",
     "title": {
      "he": "מחוויה ליצירה, חלק א: ניסויים",
      "en": "From Experience to Artwork, Part 1: Experiments"
     }
    },
    {
     "path": "lessons/experience-artwork.html",
     "title": {
      "he": "מחוויה ליצירה, חלק ב: פיתוח עבודה",
      "en": "From Experience to Artwork, Part 2: Developing a Work"
     }
    },
    {
     "path": "lessons/unit-summary.html",
     "title": {
      "he": "✦ סיכום היחידה: מה נשאר איתי",
      "en": "✦ Unit Summary: What Stays With Me"
     }
    }
   ]
  },
  {
   "id": "unit02",
   "title": {
    "he": "מבט החוצה",
    "en": "Looking Outward"
   },
   "lessons": [
    {
     "path": "lessons/lesson-2-1.html",
     "title": {
      "he": "דפוסים בטבע ובאמנות",
      "en": "Patterns in Nature & Art"
     }
    },
    {
     "path": "lessons/lesson-2-3.html",
     "title": {
      "he": "מקרוב מאוד",
      "en": "Up Close"
     }
    },
    {
     "path": "lessons/lesson-2-2.html",
     "title": {
      "he": "אותו דבר, אור אחר",
      "en": "Same Thing, Different Light"
     }
    },
    {
     "path": "lessons/lesson-2-4.html",
     "title": {
      "he": "איפה אני במרחב?",
      "en": "Where Am I in the Space?"
     }
    },
    {
     "path": "lessons/lesson-2-5.html",
     "title": {
      "he": "לתפוס תנועה",
      "en": "Catching Movement"
     }
    },
    {
     "path": "lessons/lesson-2-6.html",
     "title": {
      "he": "כשהציור עצמו נע",
      "en": "When the Drawing Itself Moves"
     }
    }
   ]
  },
  {
   "id": "unit03",
   "title": {
    "he": "מוזיקה וריתמוס כמקור השראה",
    "en": "Music & Rhythm as Inspiration"
   },
   "lessons": []
  },
  {
   "id": "unit04",
   "title": {
    "he": "זיכרון וזהות כמקור השראה",
    "en": "Memory & Identity as Inspiration"
   },
   "lessons": []
  },
  {
   "id": "unit05",
   "title": {
    "he": "תרבות וסמלים כמקור השראה",
    "en": "Culture & Symbols as Inspiration"
   },
   "lessons": []
  },
  {
   "id": "unit06",
   "title": {
    "he": "סגנון אישי כמקור השראה",
    "en": "Personal Style as Inspiration"
   },
   "lessons": []
  }
 ],
 "legacy": [
  {
   "id": "legacy0",
   "title": {
    "he": "הצתת הניצוץ",
    "en": "Igniting the Spark"
   },
   "lessons": [
    {
     "path": "lessons/lesson-01.html",
     "title": {
      "he": "מה זו השראה?",
      "en": "What is Inspiration?"
     }
    }
   ]
  },
  {
   "id": "legacy1",
   "title": {
    "he": "העולם הפנימי",
    "en": "The Inner World"
   },
   "lessons": [
    {
     "path": "lessons/lesson-02.html",
     "title": {
      "he": "רגש כמקור, מהבטן אל הקנבס",
      "en": "Emotion as Source, From Gut to Canvas"
     }
    },
    {
     "path": "lessons/lesson-03.html",
     "title": {
      "he": "מעבדת האמן: פרידה קאלו",
      "en": "Artist Lab: Frida Kahlo"
     }
    }
   ]
  },
  {
   "id": "legacy2",
   "title": {
    "he": "העולם הטבעי",
    "en": "The Natural World"
   },
   "lessons": [
    {
     "path": "lessons/lesson-04.html",
     "title": {
      "he": "אור, אווירה ומים",
      "en": "Light, Atmosphere & Water"
     }
    },
    {
     "path": "lessons/lesson-05.html",
     "title": {
      "he": "מרקמים, עונות ופרטים זעירים",
      "en": "Textures, Seasons & Tiny Details"
     }
    },
    {
     "path": "lessons/lesson-06.html",
     "title": {
      "he": "פלטות צבע מהטבע",
      "en": "Color Palettes from Nature"
     }
    },
    {
     "path": "lessons/lesson-07.html",
     "title": {
      "he": "וואבי-סאבי: יופי הפגמים",
      "en": "Wabi-Sabi: Beauty of Imperfection"
     }
    }
   ]
  },
  {
   "id": "legacy3",
   "title": {
    "he": "מוזיקה ואבסטרקט",
    "en": "Music & Abstract"
   },
   "lessons": [
    {
     "path": "lessons/lesson-08.html",
     "title": {
      "he": "כשאמנות פוגשת אמנות",
      "en": "When Art Meets Art"
     }
    },
    {
     "path": "lessons/lesson-09.html",
     "title": {
      "he": "מעבדת האמן: קנדינסקי + אימפרוביזציה",
      "en": "Artist Lab: Kandinsky + Improvisation"
     }
    }
   ]
  },
  {
   "id": "legacy4",
   "title": {
    "he": "העולם האורבני",
    "en": "The Urban World"
   },
   "lessons": [
    {
     "path": "lessons/lesson-10.html",
     "title": {
      "he": "אנשים, פנים וגיאומטריה עירונית",
      "en": "People, Faces & Urban Geometry"
     }
    },
    {
     "path": "lessons/lesson-11.html",
     "title": {
      "he": "מעבדת האמן: אדוארד הופר",
      "en": "Artist Lab: Edward Hopper"
     }
    }
   ]
  },
  {
   "id": "legacy5",
   "title": {
    "he": "העולם הביתי",
    "en": "The Home World"
   },
   "lessons": [
    {
     "path": "lessons/lesson-12.html",
     "title": {
      "he": "חפצים, שולחנות וחלונות",
      "en": "Objects, Tables & Windows"
     }
    },
    {
     "path": "lessons/lesson-13.html",
     "title": {
      "he": "דרמת האור הביתי",
      "en": "Drama of Home Light"
     }
    }
   ]
  },
  {
   "id": "legacy6",
   "title": {
    "he": "פרוטוקול הסטודיו",
    "en": "Studio Protocol"
   },
   "lessons": [
    {
     "path": "lessons/lesson-14.html",
     "title": {
      "he": "ללמוד מאמנים, שאל למה, לא מה",
      "en": "Learn from Artists, Ask Why, Not What"
     }
    }
   ]
  }
 ]
};
window.LESSON_PAGES_INDEX = {
 "lessons/lesson-1-1.html": "lesson-pages/lesson-1-1.html",
 "lessons/emotion-drawing.html": "lesson-pages/emotion-drawing.html",
 "lessons/visual-journal.html": "lesson-pages/visual-journal.html",
 "lessons/memory-drawing.html": "lesson-pages/memory-drawing.html",
 "lessons/journal-artwork.html": "lesson-pages/journal-artwork.html",
 "lessons/frida-kahlo.html": "lesson-pages/frida-kahlo.html",
 "lessons/experience-experiments.html": "lesson-pages/experience-experiments.html",
 "lessons/experience-artwork.html": "lesson-pages/experience-artwork.html",
 "lessons/unit-summary.html": "lesson-pages/unit-summary.html",
 "lessons/lesson-2-1.html": "lesson-pages/lesson-2-1.html",
 "lessons/lesson-2-2.html": "lesson-pages/lesson-2-2.html",
 "lessons/lesson-2-3.html": "lesson-pages/lesson-2-3.html",
 "lessons/lesson-2-4.html": "lesson-pages/lesson-2-4.html",
 "lessons/lesson-2-5.html": "lesson-pages/lesson-2-5.html",
 "lessons/lesson-2-6.html": "lesson-pages/lesson-2-6.html"
};
